<a href="https://colab.research.google.com/github/ParthiviKhatri2307/Account_Closure_Prediction/blob/main/Account_Closure_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [ ]:
data=pd.read_csv("Churn_Modelling.csv")
x=data.iloc[:,3:-1].values
y=data.iloc[:,-1].values
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder
la=LabelEncoder()
x[:,2]=la.fit_transform(x[:,2])
x

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
cl=ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x=np.array(cl.fit_transform(x))
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [ ]:
from sklearn.preprocessing import StandardScaler
st=StandardScaler()
x_train=st.fit_transform(x_train)
x_test=st.fit_transform(x_test)

In [ ]:
ANN=tf.keras.models.Sequential()

In [ ]:
ANN.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [ ]:
ANN.add(tf.keras.layers.Dense(units=6, activation='relu'))
ANN.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [ ]:
ANN.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [ ]:
ANN.fit(x_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6220 - accuracy: 0.7269
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4853 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4526 - accuracy: 0.7995
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4339 - accuracy: 0.8076
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4183 - accuracy: 0.8117
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4046 - accuracy: 0.8146
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3939 - accuracy: 0.8183
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3857 - accuracy: 0.8198
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3796 - accuracy: 0.8202
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3748 - accura

In [ ]:
print(ANN.predict(st.transform([[1, 0, 0, 300, 1, 43, 1, 1000, 1, 0, 1, 60000]])) > 0.5)

1/1 [==============================] - 0s 76ms/step
[[False]]


In [ ]:
print(ANN.predict(st.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 18ms/step
[[False]]


In [ ]:
y_pred=ANN.predict(x_test)
y_pred= (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
cf=confusion_matrix(y_test, y_pred)
cf

array([[1525,   70],
       [ 204,  201]])

In [ ]:
print(accuracy_score(y_test, y_pred))

0.863
